defaults:
  - cluster: h100
  - checkpoint: uma_sm
  - _self_

benchmark_name: adsorbml

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 100
    slurm:
      account: ${cluster.account}
      qos: ${cluster.qos}
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: uma-benchmarks
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.adsorbml_runner.AdsorbMLRunner
  calculator:
    _target_: fairchem.core.FAIRChemCalculator.from_model_checkpoint
    name_or_path: ${checkpoint.ckpt_path}
    task_name: oc20
  input_data_path: ${cluster.data_root_dir}/catalysis/adsorbml/adsorbml_slabs_adsorbates_targets.pkl
  num_placements: 100
  adsorption_energy_model: False
  save_relaxed_atoms: True
  fmax: 0.02
  steps: 300
  optimizer_cls:
    _target_: ase.optimize.LBFGS
    _partial_: True
    maxstep: 0.2
    memory: 50
    damping: 1.2
    alpha: 80

reducer:
  _target_: fairchem.core.components.benchmark.adsorbml_reducer.AdsorbMLReducer
  target_data_key: energy
  benchmark_name: ${benchmark_name}
  index_name: sid
