defaults:
  - cluster: h100
  - checkpoint: uma_sm
  - _self_

benchmark_name: hea-is2re

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 500
    slurm:
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: uma-benchmarks
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.relaxation_runner.RelaxationRunner
  calculator:
    _target_: fairchem.core.FAIRChemCalculator.from_model_checkpoint
    name_or_path: ${checkpoint.ckpt_path}
    task_name: omat
  input_data:
    _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
    config:
      src: ${cluster.data_root_dir}/materials/hea/is2re
  save_relaxed_atoms: False
  calculate_properties: [ "energy" ]
  save_target_properties: [ "energy" ]
  fmax: 0.02
  steps: 500
  optimizer_cls:
    _target_: ase.optimize.FIRE
    _partial_: True
  cell_filter_cls:
    _target_: ase.filters.FrechetCellFilter
    _partial_: True
  normalize_properties_by:
    energy: natoms

reducer:
  _target_: fairchem.core.components.benchmark.benchmark_reducer.JsonDFReducer
  target_data_keys: ["energy_per_atom"]
  benchmark_name: ${benchmark_name}
  index_name: sid
