defaults:
  - cluster: h100
  - checkpoint: uma_sm
  - _self_

benchmark_name: nve-md-omat-100ps

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 27
    slurm:
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: uma-benchmarks
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.nve_md_runner.NVEMDRunner
  calculator:
    _target_: fairchem.core.FAIRChemCalculator.from_model_checkpoint
    name_or_path: ${checkpoint.ckpt_path}
    task_name: omat

  input_data:
    _target_: fairchem.core.components.calculate.nve_md_runner.get_nve_md_data
    dataset_root: ${cluster.data_root_dir}/md
    dataset_name: tm23
  time_step: 5.
  steps: 20000

reducer:
  _target_: fairchem.core.components.benchmark.nvemd_reducer.NVEMDReducer
  benchmark_name: ${benchmark_name}
