defaults:
  - cluster: v100
  - checkpoint: uma_sm
  - _self_

benchmark_name: omc-is2re-polymorphs

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 1030
    slurm:
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: uma-benchmarks
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.relaxation_runner.RelaxationRunner
  calculator:
    _target_: fairchem.core.FAIRChemCalculator.from_model_checkpoint
    name_or_path: ${checkpoint.ckpt_path}
    task_name: omc
  input_data:
    _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
    config:
      src: ${cluster.data_root_dir}/omc/7bt-polymorphs/7bt-polymorphs-is.aselmdb
  save_relaxed_atoms: True
  calculate_properties: [ "energy" ]
  save_target_properties: ["energy", "molecule_id", "atoms_relaxed"]
  normalize_properties_by:
    energy: nmolecules
  fmax: 0.01
  steps: 500
  optimizer_cls:
    _target_: ase.optimize.BFGS
    _partial_: True
  cell_filter_cls:
    _target_: ase.filters.FrechetCellFilter
    _partial_: True

reducer:
  _target_: fairchem.core.components.benchmark.omc_polymorph_reducer.OMCPolymorphReducer
  benchmark_name: ${benchmark_name}
  target_data_key: "energy_per_nmolecules"
  molecule_id_key: "molecule_id_target"
  calculate_structural_metrics: True
  index_name: sid
