# build the documentation and upload the built artifact
name: build documentation

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: 4-core-ubuntu-gpu-t4

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        # Optional: get full history if needed
        fetch-depth: 0

    - name: Install pandoc
      run: sudo apt-get -y install pandoc

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e packages/fairchem-core[docs,adsorbml,quacc] -e packages/fairchem-data-oc[dev] -e packages/fairchem-applications-cattsunami

    # Build the book
    - name: Build the book
      env:
        QUACC_CONFIG_FILE: docs/.quacc.yml
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Set FAST_DOCS only if not a push to main
        FAST_DOCS: ${{ (github.event_name != 'push' || github.ref != 'refs/heads/main') && 'true' || '' }}
      run: |
        # Convert MyST markdown files to Jupyter notebooks if needed to get download as ipynb buttons
        jupytext --to ipynb ./docs/uma_tutorials/uma_tutorial.md
        # find ./docs/ -name "*.md" -exec grep -q "format_name: myst" {} \; -print0 | xargs -0 jupytext --to ipynb
        jupyter-book build docs

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-html
        path: docs/_build/html/*
